language: objective-c
osx_image: xcode8.1

before_install:
    - echo -e "machine github.com\n login $CI_USER_TOKEN" >> ~/.netrc
    - gem update fastlane --no-ri --no-rdoc --no-document

script:
    - fastlane test
