language: objective-c
osx_image: xcode8.1

before_install:
    - echo -e "machine github.com\n login $CI_USER_TOKEN" >> ~/.netrc
    - gem update fastlane --no-ri --no-rdoc --no-document

script:
    - if [[ "$TRAVIS_BRANCH" == "master" ]]; then fastlane beta; fi
    - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then fastlane test; fi