fastlane_version "1.108.0"
default_platform :ios

platform :ios do
  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to HockeyApp"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    increment_build_number(
      build_number: number_of_commits
    )
    match(type: "adhoc", readonly: true)
    gym(
      clean: true
    )
    hockey(
      api_token: ENV["HOCKEY_API_TOKEN"],
      notify: '1'
    )
  end
end
